
---
title: "| Data Science With an Eye Towards Sustainability    \n| P6: Narrowing Your Project Topic\n"
author: "Joe, Peter, Anna, Quinn"
output:
  bookdown::html_document2:
    split_by: none
    toc: no
---

Each group should hand in one html document for the following exercises. Throughout the exercises, keep in mind that your research topics, questions, and data might evolve throughout the course of the project. This checkpoint is simply a first step in narrowing these down.

\

# Names & Workflow

List all group members. Discuss a plan for completing this assignment. How will you put together your shared Rmd? How will you divide the work? When will you meet to work on the assignment? Write this down in your Rmd.

In addition to class, we will have weekly meetings on Friday mornings

Also, if you are using one, write down your GitHub repository.

-   We will be using GitHub:

-   Shared RMD/Project files will be set up as needed

-   Project development plan: work together until we find 1-2 solid directions, then split into two smaller working groups
* depending on motivations.... Joe and Anna will split off and work on a data project using DJS JE data. 

\

# Topic & Research Questions

Following on the conversations you've already had in the preliminary brainstorming exercises, identify a common research topic of interest.

Specify two to three potential research questions that (1) are related to the topic above; and (2) you can (at least partially) answer using data.


- How have state and Federal incentives impacted the adoption of residential rooftop solar in Massachusetts*? 

- How is solar adoption and type of solar facility variable within socioeconomic factors across county/townships in Massachusetts*? And how does this correlate to incentives in these areas?

*Depending on how this goes, we hope to do a comparison to another state... 
**Depending on the data we can find, we may look into specific towns and their insentives if we don't find a larger comprehensive dataset. 

The Brainstormer corner

-   State/Federal incentives - how do they impact adoption rates of renewable?

-   Narrowed that to residential adoption of renewable OR utilities scale

-   where is solar specifically being adopted? are there patterns or exceptions? do those exceptions have good incentives associated?

-   incentives across states - correlated with adoption rate?

-   how does this adoption relate to per-capita energy consumption or prices

-   STEADy - data set describing how feasible solar adoption is based on physical and socioeconomic
    -   identifies where federal/state incentives are applicable\ (this is piece of data I will experiment with)

# Connections to Sustainability

How are your research questions connected to sustainability? What are your personal learning goals related to sustainability for this project? You may wish to refer back to the [UN Sustainable Development Goals](https://sdgs.un.org/goals), the [Inner Development Goals](https://innerdevelopmentgoals.org/), and the [Engineering for One Planet](https://engineeringforoneplanet.org/wp-content/uploads/EOP_Framework_2023.pdf?), [Six Pillars of Climate Justice](https://centerclimatejustice.universityofcalifornia.edu/what-is-climate-justice/), and [Just Transition Principles](https://climatejusticealliance.org/just-transition/) frameworks. As a team, what sustainability background, analysis, and storytellling do you want to include in the scope of your project and in your final artifacts?


`#7 affordable and clean energy 
<<<<<<< HEAD
We are curious as to the roles incentives play in achieving this sdg of clean energy, and the consequences this solar siting may have for establishing a "just" energy transition. 


=======
>>>>>>> 752b0dcfe9af4782792e30e035819a18ad6d98f1
\

# Data

Identify the data sets you will use to explore the research questions above. These data sets may already be in csv form, you may acquire them (e.g., scraped with rvest, via public API, or from an SQL database), or you may plan on collecting some extra data. For each data set, summarize the following:


https://sunroof.withgoogle.com/
This is a data set of the residential solar potential based on sun exposure from google earth. It is a continuously maintained data base and includes the current count of number of panels. 
600000 ob over 31 variables, broken by census tract f

masscec.com/production-tracking-system-pts#data
The Solar PV systems report from 2024 tracks the solar sites in Mass which are registered in the PTS system. This measures date, location, cost, output and the developers. 
This is limited by only tracking the projects which have complete PTS registration.It is a 143151ob over 17var data set, and could be joined with other data around town and county 

Tracking the sun:
This is a data set which has state specific info about all the projets, including rebate recieved, and customer segment, solar sell tilt. and effecency... it is large and a lot of missing information for may columns 
it is 140908ob over 80vars. data.openei.org/submissions/3




-   data source
-   data description - what's being measured?
-   data limitations (eg: are the data recent? do they contain all variables you might want?)
-   data dimensions - how much data do you have?
-   how might the data be joined with other data you have?

\

# Research Question 1

Restate research question 1. Construct 3-4 relevant visualizations that provide insight on / help answer this question and piece these together to tell a short story. For each visualization, 1-2 sentences will suffice.

- How have state and Federal incentives impacted the adoption of residential rooftop solar in Massachusetts over time*? 

**peter- make visualization about average grant size and location of residential solar


\

# Research Question 2 

How is solar adoption and type of solar facility variable within socioeconomic factors across county/townships in Massachusetts*? And how does this correlate to incentives in these areas?


***quinn - make visualization about hot spots of solar adoption and sun exposure using sunroof data. 

***joe - fit linear model about house income and solar rates 
\

# Next Steps

Identify next steps in your analysis. Do you need additional data? Do you need to do more cleaning or wrangling? How might you narrow your research questions/hypotheses? What additional visualizations would be helpful?

\

# Contributions

Summarize each group member's specific contributions to this checkpoint assignment.
